In [3]:
# Завдання 1. Створіть одновимірний масив (вектор) з перших 10-ти додатних парних чисел та виведіть його значення.

import numpy as np

vector = np.arange(2, 21, 2)

print("Вектор з перших 10 додатних парних чисел:")
print(vector)

Вектор з перших 10 додатних парних чисел:
[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
# Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3,
# заповніть його сумою кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

import numpy as np

values = []
for i in range(1, 10):
    values.append(i + (i - 1))

matrix = np.array(values).reshape(3, 3)

print("Матриця 3x3:")
print(matrix)

Матриця 3x3:
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [5]:
# Завдання 3. Створіть масив розміром 2x3, заповніть його випадковими цілими числами
# в діапазоні від -1 до 1 та виведіть його значення.

import numpy as np

matrix = np.random.randint(-1, 2, size=(2, 3))

print("Матриця 2x3 зі значеннями від -1 до 1:")
print(matrix)

Матриця 2x3 зі значеннями від -1 до 1:
[[ 1  0 -1]
 [-1 -1  1]]


In [6]:
# Завдання 4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами
# в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

import numpy as np

matrix = np.random.rand(5, 5)

row_sums = np.sum(matrix, axis=1)

column_vector = row_sums.reshape(5, 1)

print("Матриця 5x5:")
print(matrix)

print("\nВектор-стовпчик (сума елементів рядків):")
print(column_vector)

Матриця 5x5:
[[0.56083149 0.71361827 0.53104835 0.56792214 0.50262175]
 [0.92383794 0.84289514 0.88702008 0.14029569 0.02701887]
 [0.21361985 0.84332009 0.39379757 0.81275962 0.00598737]
 [0.23500467 0.44451402 0.11065576 0.41497866 0.59582771]
 [0.9834257  0.05944387 0.58009772 0.66800284 0.71532715]]

Вектор-стовпчик (сума елементів рядків):
[[2.87604199]
 [2.82106772]
 [2.2694845 ]
 [1.80098082]
 [3.00629729]]


In [7]:
# Завдання 5. Створіть два одновимірних масиви розміром 5,
# заповніть їх випадковими дійсними числами від 0 до 1
# та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

a = np.random.rand(5)
b = np.random.rand(5)

add = a + b
sub = a - b
mul = a * b

print("Масив A:", a)
print("Масив B:", b)

print("\nПоелементне додавання (A + B):", add)
print("Поелементне віднімання (A - B):", sub)
print("Поелементне множення (A * B):", mul)

Масив A: [0.08595433 0.24786524 0.77161231 0.29588293 0.58832148]
Масив B: [0.48637426 0.43127709 0.23513635 0.21888973 0.22818824]

Поелементне додавання (A + B): [0.5723286  0.67914233 1.00674866 0.51477267 0.81650972]
Поелементне віднімання (A - B): [-0.40041993 -0.18341184  0.53647596  0.0769932   0.36013324]
Поелементне множення (A * B): [0.04180598 0.1068986  0.1814341  0.06476574 0.13424804]


In [8]:
# Завдання 6. Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 5 до 30
# та знайдіть їх добуток.

import numpy as np

A = np.random.uniform(5, 30, (3, 3))
B = np.random.uniform(5, 30, (3, 3))

C = np.dot(A, B)

print("Матриця A:\n", A)
print("\nМатриця B:\n", B)
print("\nДобуток матриць A * B:\n", C)

Матриця A:
 [[23.43954675 14.14617049 14.53727204]
 [11.33077867  9.81376458 27.91727954]
 [10.49473808  6.57558611 27.63844996]]

Матриця B:
 [[22.51514729 20.81385333 24.14557734]
 [ 7.89792797 21.99425159 13.16082986]
 [12.16954476 11.53198862 26.06907771]]

Добуток матриць A * B:
 [[ 816.38226581  966.64537658 1131.11000636]
 [ 672.36313925  773.62532244 1130.5232082 ]
 [ 624.5714329   681.78732468 1060.45057968]]


In [9]:
# Завдання 7. Створіть дві матриці розміром 2x3 та 3x4,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

import numpy as np

A = np.random.randint(1, 6, size=(2, 3))  # 2x3
B = np.random.randint(1, 6, size=(3, 4))  # 3x4

C = np.dot(A, B)

print("Матриця A (2x3):\n", A)
print("\nМатриця B (3x4):\n", B)
print("\nДобуток матриць A * B (2x4):\n", C)

Матриця A (2x3):
 [[2 3 4]
 [4 4 1]]

Матриця B (3x4):
 [[4 1 2 1]
 [5 1 2 1]
 [2 2 5 4]]

Добуток матриць A * B (2x4):
 [[31 13 30 21]
 [38 10 21 12]]


In [10]:
# Завдання 8. Створіть матрицю розміром 3x3,
# заповніть її випадковими цілими числами в діапазоні від 1 до 8
# та знайдіть її обернену матрицю.

import numpy as np

A = np.random.randint(1, 9, size=(3, 3))

print("Матриця A:")
print(A)

det = np.linalg.det(A)

if det != 0:
    A_inv = np.linalg.inv(A)
    print("\nОбернена матриця A⁻¹:")
    print(A_inv)
else:
    print("\nМатриця є виродженою (det=0), оберненої матриці не існує.")

Матриця A:
[[3 3 6]
 [3 5 2]
 [4 2 3]]

Обернена матриця A⁻¹:
[[-0.2037037  -0.05555556  0.44444444]
 [ 0.01851852  0.27777778 -0.22222222]
 [ 0.25925926 -0.11111111 -0.11111111]]


In [11]:
# Завдання 9. Створіть матрицю розміром 4x4,
# заповніть її випадковими дійсними числами в діапазоні від 0 до 1
# та транспонуйте її.

import numpy as np

A = np.random.rand(4, 4)

print("Матриця A:")
print(A)

A_T = A.T

print("\nТранспонована матриця Aᵀ:")
print(A_T)

Матриця A:
[[0.80121704 0.64076663 0.44195958 0.58334279]
 [0.01295314 0.41454341 0.49428507 0.77505109]
 [0.20655299 0.94396014 0.21958772 0.31650507]
 [0.50258841 0.18090894 0.86187605 0.85908787]]

Транспонована матриця Aᵀ:
[[0.80121704 0.01295314 0.20655299 0.50258841]
 [0.64076663 0.41454341 0.94396014 0.18090894]
 [0.44195958 0.49428507 0.21958772 0.86187605]
 [0.58334279 0.77505109 0.31650507 0.85908787]]


In [12]:
# Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1,
# заповніть їх випадковими дійсними числами від 0 до 1,
# знайдіть добуток матриці на вектор.

import numpy as np

A = np.random.rand(3, 4)

v = np.random.rand(4, 1)

result = np.dot(A, v)

print("Матриця A (3x4):\n", A)
print("\nВектор v (4x1):\n", v)
print("\nДобуток A * v (3x1):\n", result)

Матриця A (3x4):
 [[0.24609139 0.05416039 0.96814252 0.69853425]
 [0.65001913 0.16807263 0.0463416  0.97039211]
 [0.21287959 0.41402169 0.13188914 0.40939782]]

Вектор v (4x1):
 [[0.10741725]
 [0.06659357]
 [0.82566126]
 [0.48579557]]

Добуток A * v (3x1):
 [[1.16874381]
 [0.59069047]
 [0.35821752]]


In [13]:
# Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1,
# заповніть матрицю випадковими цілими числами (1..10),
# вектор випадковими дійсними числами (0..1),
# знайдіть добуток матриці на вектор.

import numpy as np

A = np.random.randint(1, 11, size=(2, 3))

v = np.random.rand(3, 1)

result = np.dot(A, v)

print("Матриця A (2x3):\n", A)
print("\nВектор v (3x1):\n", v)
print("\nДобуток A * v (2x1):\n", result)

Матриця A (2x3):
 [[5 3 7]
 [8 1 3]]

Вектор v (3x1):
 [[0.85295389]
 [0.87320287]
 [0.44928065]]

Добуток A * v (2x1):
 [[10.02934264]
 [ 9.04467597]]


In [14]:
# Завдання 12. Створіть дві матриці розміром 7x7,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10
# та знайдіть їхню різницю.

import numpy as np

A = np.random.randint(1, 11, size=(7, 7))
B = np.random.randint(1, 11, size=(7, 7))

C = A - B

print("Матриця A:\n", A)
print("\nМатриця B:\n", B)
print("\nРізниця матриць (A - B):\n", C)

Матриця A:
 [[ 1  1  8  6  5  2  1]
 [ 5  4  1  7  8  3  3]
 [ 3  9  8  6  7  2  4]
 [ 6  4  7 10  5  2  3]
 [ 7  3  4  1  8  2  6]
 [ 1  2  1  6  8  8  5]
 [ 9  6  5  2  6  6  8]]

Матриця B:
 [[ 8  6  2  3 10  7  6]
 [ 3  8  2  7 10  5  6]
 [ 1  1 10  8  3  5  8]
 [ 8  6  5  8  9  3  2]
 [ 5  1  1  5  8  9  1]
 [10  8 10  1  2  7  1]
 [ 3  8  6  2  1  7  2]]

Різниця матриць (A - B):
 [[-7 -5  6  3 -5 -5 -5]
 [ 2 -4 -1  0 -2 -2 -3]
 [ 2  8 -2 -2  4 -3 -4]
 [-2 -2  2  2 -4 -1  1]
 [ 2  2  3 -4  0 -7  5]
 [-9 -6 -9  5  6  1  4]
 [ 6 -2 -1  0  5 -1  6]]


In [15]:
# Завдання 13. Створіть дві матриці розміром 7x7,
# заповніть їх випадковими цілими числами в діапазоні від -10 до 10
# та знайдіть суму їх елементів.

import numpy as np

A = np.random.randint(-10, 11, size=(7, 7))
B = np.random.randint(-10, 11, size=(7, 7))

sum_A = np.sum(A)
sum_B = np.sum(B)

total_sum = sum_A + sum_B

print("Матриця A:\n", A)
print("\nСума елементів матриці A:", sum_A)

print("\nМатриця B:\n", B)
print("\nСума елементів матриці B:", sum_B)

print("\nЗагальна сума елементів обох матриць:", total_sum)

Матриця A:
 [[  7  -5  -8  -7   5   6   4]
 [  2  -7   1  -2  -8  -8   5]
 [  3   1   5  -4   2   2  -8]
 [  7  -7  -2  -2 -10  -5   0]
 [ -1   0   5   2   2  -3  -9]
 [ 10   3   8  -9  -5  -3  -7]
 [ -7   0   6   4  -2   8  -3]]

Сума елементів матриці A: -34

Матриця B:
 [[  5   4  -1   9   0  -2  10]
 [  4  -3  -4  -2   3   4  10]
 [ -4  -5  -1  10   8   8   6]
 [ -1  10  -4  -9   2   6  -1]
 [ -5  -8  -4   6  -4  -6   7]
 [  1   8  10   4  -3   1 -10]
 [ -4   7  -6  -5   9 -10 -10]]

Сума елементів матриці B: 40

Загальна сума елементів обох матриць: 6


In [16]:
# Завдання 14. Створіть матрицю розміром 3x3,
# заповніть її випадковими цілими числами в діапазоні від 1 до 10
# та знайдіть середнє арифметичне значення елементів матриці.

import numpy as np

A = np.random.randint(1, 11, size=(3, 3))

mean_value = np.mean(A)

print("Матриця A:\n", A)
print("\nСереднє арифметичне значення елементів:", mean_value)

Матриця A:
 [[7 3 5]
 [8 4 2]
 [2 4 6]]

Середнє арифметичне значення елементів: 4.555555555555555


In [17]:
# Завдання 15. Створіть матрицю розміром 8x8,
# заповніть її випадковими дійсними числами в діапазоні від -1 до 1
# та знайдіть вектор-стовпчик, що містить найменший елемент у кожному рядку.

import numpy as np

A = np.random.uniform(-1, 1, size=(8, 8))

min_values = np.min(A, axis=1).reshape(8, 1)

print("Матриця A (8x8):\n", A)
print("\nВектор-стовпчик з мінімальними елементами рядків:\n", min_values)

Матриця A (8x8):
 [[ 0.59834614  0.00274725 -0.5641252   0.10994851 -0.1810327  -0.57199157
  -0.11013867  0.76153031]
 [-0.1440002  -0.63302839 -0.08720746  0.55872605  0.40513478 -0.48553684
  -0.30007691  0.53407395]
 [ 0.02580961 -0.39275644 -0.53972377  0.29122394  0.16811218 -0.99580127
  -0.20377356 -0.00202197]
 [ 0.18943767 -0.62798262  0.81141572 -0.83762321 -0.83775477  0.97856709
   0.3907545   0.91404844]
 [-0.70792676 -0.35469254  0.84621324 -0.2260087   0.42669251 -0.85062215
   0.04202226 -0.90720315]
 [-0.10999426  0.66489621 -0.43652954 -0.31927616  0.66480818 -0.35884845
  -0.43375795  0.34651747]
 [ 0.98858252  0.86313394  0.57506668  0.28686893 -0.44125857 -0.26369277
  -0.38579706 -0.10726639]
 [-0.24821763  0.84794646  0.83227589  0.41165504 -0.33554885 -0.25824663
  -0.46210259  0.49695358]]

Вектор-стовпчик з мінімальними елементами рядків:
 [[-0.57199157]
 [-0.63302839]
 [-0.99580127]
 [-0.83775477]
 [-0.90720315]
 [-0.43652954]
 [-0.44125857]
 [-0.46210259]]
